spring.application.name=library
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=library;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.config.import=optional:application.private.properties

# Email configuration for sending emails
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# PayOS
payos.client-id=39a9fc3f-cedb-4384-9cc4-0c837d348975
payos.api-key=d39f6818-dbea-4fe1-ab8e-0696b4cf685b
payos.checksum-key=93ea2a5948c5387ef99f635361dc78467a04d2fe9490ccc28885c4be65ff8df2

# Pinecone
spring.ai.vectorstore.pinecone.apiKey=pcsk_4Xsp4K_BEdAbeu8ohP5UgG9ZTCogzUTnaDAuYYCfHA1jt8pLPAcUU9aice5iTE3i2x831e
spring.ai.vectorstore.pinecone.index-name=library
spring.ai.vectorstore.pinecone.index-host=https://library-j5id1fj.svc.aped-4627-b74a.pinecone.io

# GenAI
spring.ai.model.embedding=ollama
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.embedding.options.model=nomic-embed-text:v1.5

spring.ai.google.genai.api-key=AQ.Ab8RN6Ka3GatME9bZfGiuCYcoZwmsGAIESYoRQdKBDwRweQtYQ
spring.ai.google.genai.chat.options.model=gemini-3.1-flash-lite
spring.ai.model.chat=google-genai

# Session timeout configuration
server.servlet.session.timeout=15m

# Session management configuration
spring.session.jdbc.initialize-schema=always