spring.application.name=library
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=library;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.config.import=optional:application.private.properties

# Email configuration for sending emails
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# PayOS
payos.client-id=e6ca27b1-ee21-4152-9aef-c710542fb2e8
payos.api-key=03cd9439-5824-4a62-a3fa-1fef7885f6a8
payos.checksum-key=e2bbcf35014f24649ebeae76ef360c4c7e4594fd1f16cefc2ef3d3468d019999

# Pinecone
spring.ai.vectorstore.pinecone.apiKey=pcsk_612vMX_ChTJZNqrU9LcrL6SKiZwiMy1zajrcjBg1qLW1a3PjvAhhyHFBFrxvNYoQJnycdc
spring.ai.vectorstore.pinecone.index-host=https://library-ai-ps6n51j.svc.aped-4627-b74a.pinecone.io
spring.ai.vectorstore.pinecone.index-name=library-ai
spring.ai.vectorstore.pinecone.namespace=default

# GenAI
spring.ai.google.genai.api-key=AIzaSyALBnT9dlQGtgW7f3LJn6s8nP02VivdGwA

# Session timeout configuration
server.servlet.session.timeout=15m

# Session management configuration
spring.session.jdbc.initialize-schema=always